create extension if not exists pgcrypto;
create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 username text unique, display_name text, bio text, profile_photo_url text,
 is_private boolean not null default false,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.interests(
 id bigint generated by default as identity primary key,
 name text unique not null, slug text unique not null, category text,
 description text, is_active boolean default true
);
create table if not exists public.user_interests(
 user_id uuid references auth.users(id) on delete cascade,
 interest_id bigint references public.interests(id) on delete cascade,
 source text default 'selected', strength real default 1,
 created_at timestamptz default now(), updated_at timestamptz default now(),
 primary key(user_id,interest_id)
);
create table if not exists public.posts(
 id uuid primary key default gen_random_uuid(),
 author_id uuid not null references auth.users(id) on delete cascade,
 text text, content_type text default 'text', visibility text default 'public',
 status text default 'published', created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.follows(
 follower_id uuid references auth.users(id) on delete cascade,
 following_id uuid references auth.users(id) on delete cascade,
 status text default 'accepted', created_at timestamptz default now(),
 primary key(follower_id,following_id), check(follower_id<>following_id)
);
create table if not exists public.comments(
 id uuid primary key default gen_random_uuid(),
 post_id uuid references public.posts(id) on delete cascade,
 author_id uuid references auth.users(id) on delete cascade,
 parent_id uuid references public.comments(id) on delete cascade,
 body text not null, created_at timestamptz default now()
);
create table if not exists public.interactions(
 user_id uuid references auth.users(id) on delete cascade,
 post_id uuid references public.posts(id) on delete cascade,
 kind text not null, created_at timestamptz default now(),
 primary key(user_id,post_id,kind)
);
create table if not exists public.recommendation_events(
 id bigint generated by default as identity primary key,
 user_id uuid references auth.users(id) on delete cascade,
 content_id uuid,event_type text not null,value real,model_version text,created_at timestamptz default now()
);
create table if not exists public.reports(
 id uuid primary key default gen_random_uuid(),
 reporter_id uuid references auth.users(id) on delete cascade,
 target_type text not null,target_id uuid,reason text not null,
 status text default 'open',created_at timestamptz default now()
);
create table if not exists public.notifications(
 id uuid primary key default gen_random_uuid(),
 user_id uuid references auth.users(id) on delete cascade,
 type text not null,title text not null,body text,is_read boolean default false,created_at timestamptz default now()
);
alter table public.profiles enable row level security;
alter table public.interests enable row level security;
alter table public.user_interests enable row level security;
alter table public.posts enable row level security;
alter table public.follows enable row level security;
alter table public.comments enable row level security;
alter table public.interactions enable row level security;
alter table public.recommendation_events enable row level security;
alter table public.reports enable row level security;
alter table public.notifications enable row level security;
create policy "profiles owner" on public.profiles for all using(auth.uid()=id) with check(auth.uid()=id);
create policy "interest read" on public.interests for select using(true);
create policy "user interests owner" on public.user_interests for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "posts read" on public.posts for select using(visibility='public' or auth.uid()=author_id);
create policy "posts owner" on public.posts for all using(auth.uid()=author_id) with check(auth.uid()=author_id);
create policy "comments read" on public.comments for select using(true);
create policy "comments owner" on public.comments for all using(auth.uid()=author_id) with check(auth.uid()=author_id);
create policy "notifications owner" on public.notifications for all using(auth.uid()=user_id) with check(auth.uid()=user_id);
create policy "reports insert" on public.reports for insert with check(auth.uid()=reporter_id);
insert into public.interests(name,slug,category) values
('Technology','technology','Tech'),('Football','football','Sports'),('Cars','cars','Auto'),
('Motorcycles','motorcycles','Auto'),('Music','music','Entertainment'),('Movies','movies','Entertainment'),
('Travel','travel','Lifestyle'),('Photography','photography','Creative'),('Gaming','gaming','Entertainment'),
('Fashion','fashion','Lifestyle'),('Food','food','Lifestyle'),('Fitness','fitness','Lifestyle'),
('Business','business','Career'),('Art','art','Creative'),('Nature','nature','Lifestyle')
on conflict(slug) do nothing;
