name: nexa
description: NEXA - The Internet Around What You Care About.
publish_to: none
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/nexa_icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/nexa_icon.png"
  adaptive_icon_background: "#080817"
  adaptive_icon_foreground: "assets/icon/nexa_icon.png"
